#pragma config(Sensor, port1,  colorSensor,    sensorVexIQ_ColorHue)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setColorMode(colorSensor, colorTypeRGB_Hue_Reflected);
	delay(500);
	while(true)
	{
		displayTextLine(2, "Hue: %d", getColorHue(colorSensor));
	}
}
