#pragma config(Sensor, port1,  colorSensor,    sensorVexIQ_ColorHue)
#pragma config(Sensor, port2,  rightGrayscale, sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  leftGrayscale,  sensorVexIQ_ColorGrayscale)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftGrays[10];
int rightGrays[10];

int leftGrayscaleValue;
int rightGrayscaleValue;

void updateGrayscales()
{
	if(time1[T2] < 5)
	{
		return;
	}
	time1[T2] = 0;
	int tempLeft[10];
	int tempRight[10];
	for(int i = 0; i < 8; i++)
	{
		tempLeft[i] = leftGrays[i + 1];
		tempRight[i] = rightGrays[i + 1];
	}
	tempLeft[0] = getColorGrayscale(leftGrayscale);
	tempRight[0] = getColorGrayscale(leftGrayscale);
	leftGrays = tempLeft;
	rightGrays = tempRight;
	leftGrayscaleValue = 0;
	rightGrayscaleValue = 0;
	for(int i = 0; i < 9; i++)
	{
		leftGrayscaleValue += leftGrays[i];
		rightGrayscaleValue += rightGrays[i];
	}
	leftGrayscaleValue = leftGrayscaleValue / 10;
	rightGrayscaleValue = rightGrayscaleValue / 10;
}

task main()
{
	time1[T2] = 0;
	setColorMode(colorSensor, colorTypeRGB_Hue_Reflected);
	setColorMode(leftGrayscale, colorTypeGrayscale_Reflected);
	setColorMode(rightGrayscale, colorTypeGrayscale_Reflected);
	delay(400);
	while(true)
	{
		updateGrayscales();
		int red = getColorRedChannel(colorSensor);
		int green = getColorGreenChannel(colorSensor);
		int blue = getColorBlueChannel(colorSensor);
		if(red > blue && red > green)
		{
			displayTextLine(4, "IndividualR");
		}
		else if(blue > red && blue > green)
		{
			displayTextLine(4, "IndividualB");
		}
		else if(green > blue && green > red)
		{
			displayTextLine(4, "IndividualG");
		}
		else
		{
			displayTextLine(4, "Individual?");
		}
		if(getColorHue(colorSensor) > 0 && getColorHue(colorSensor) < 10)
		{
			displayTextLine(3, "HueR");
		}
		else if(getColorHue(colorSensor) > 160 && getColorHue(colorSensor) < 170)
		{
			displayTextLine(3, "HueB");
		}
		else if(getColorHue(colorSensor) > 100 && getColorHue(colorSensor) < 110)
		{
			displayTextLine(3, "HueG");
		}
		else
		{
			displayTextLine(3, "Hue?");
		}
		if(leftGrayscaleValue > 125)
		{
			displayTextLine(2, "LeftWhite");
		}
		else if(leftGrayscaleValue < 75)
		{
			displayTextLine(2, "LeftBlack");
		}
		else
		{
			displayTextLine(2, "Left?");
		}
		if(rightGrayscaleValue > 125)
		{
			displayTextLine(1, "RightWhite");
		}
		else if(rightGrayscaleValue < 75)
		{
			displayTextLine(1, "RightBlack");
		}
		else
		{
			displayTextLine(1, "Right?");
		}
	}
}
