#pragma config(Motor,  motor1,          rightDrive,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          leftDrive,     tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float goalValue = 50;

float currentValue = 0;

float proportionalValue = 0;

float maxChange = 1;

float proportional(float goal, float current)
{
	proportionalValue = (goal - current) * 0.1;
	/*
	if(proportionalValue > (goal-current))
	{
		proportionalValue = maxChange;
	}
	*/
	return proportionalValue;
}

task main()
{
	while(true)
	{
		wait1Msec(500);
		currentValue += proportional(goalValue, currentValue);
		if(goalValue == currentValue)
		{
			displayTextLine(5, "Finished");
		}
		else
		{
			displayTextLine(5, "");
		}
		displayTextLine(2, "current: %f", currentValue);
		displayTextLine(4, "P: %f", proportionalValue);
	}
}
