#pragma config(Motor,  motor1,          rightDrive,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          leftDrive,     tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

}
