#pragma config(Motor,  motor1,          rightDrive,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          leftDrive,     tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float goalValue = 5000;

float currentValue = 0;

float proportional(float goal, float current)
{
	float acceleration = 0;
	if(abs(goal - current) > goal - 500)//if near end of driving
	{
		acceleration = (goal - current) * -0.1;//slow down
	}
	else if(current < 500)//if at start of driving
	{
		acceleration = (current - goal) * 0.1;//speed up
	}
	else//if in the middle
	{
		acceleration = 0;//keep speed
	}
	//proportionalValue = (goal - current) * 0.1; //0.1 is your rate of change (accerlation)
	return acceleration;
}

task main()
{
	while(true)
	{
		wait1Msec(500);
		float propValue = proportional(goalValue, currentValue);
		currentValue += propValue;
		if((goalValue - currentValue) < 0.1)
		{
			currentValue = goalValue;
			displayTextLine(5, "Finished");
		}
		else
		{
			displayTextLine(5, "");
		}
		displayTextLine(2, "current: %f", currentValue);
		displayTextLine(4, "P: %f", propValue);
	}
}
